#!/bin/bash
function traslate()
{
    echo "trasladar $1 $2"
    for file in `ls $1`
    do
        echo $1
        if [[ -d $file ]]
        then
            traslate $1/$file $2
        else
            mv $1/$file $2
        fi
    done
}
cd $1
destination=`pwd`
a=`ls $1`
for i in $a
do
    if [[ -d $i ]]
    then
        traslate $i $destination
    fi
done
echo $a/$destination
