#!/bin/bash
function traslate()
{
    echo "trasladar $1 $2"
    for file in `ls $1`
    do
        if [[ -d $1/$file ]]
        then
            newDir=$1/$file
            traslate $newDir $2
            echo "trasladar $1/$file $2"
        else
            mv $1/$file $2
        fi
    done
}

if [[ $1 != "" ]]
then
cd $1
destination=`pwd`
a=`ls $1`
for i in $a
do
    if [[ -d $i ]]
    then
        traslate $i $destination
        rm -r $i
    fi
done
echo $a/$destination
else 
    echo "Sin parametro, ingrese el directorio destino porfavor"
fi
